import { chromium } from 'playwright'
const browser = await chromium.launch({ channel: 'chrome' })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1.5 })
await page.goto('http://localhost:3014/player/', { waitUntil: 'networkidle' })
await page.getByRole('button', { name: 'Start' }).click()
await page.waitForTimeout(1200)
await page.evaluate(() => document.querySelectorAll('audio').forEach((a) => (a.muted = true)))
await page.getByRole('navigation', { name: 'Slides' }).getByRole('button').nth(2).click()
await page.waitForTimeout(500)
await page.evaluate(() => { const a = document.querySelector('audio'); if (a && a.duration) a.currentTime = a.duration - 0.05 })
await page.waitForTimeout(2200)
await page.screenshot({ path: 'shots/gate-open.png' })
await page.getByRole('button', { name: 'Collapse contents' }).click()
await page.waitForTimeout(700)
await page.screenshot({ path: 'shots/gate-collapsed.png' })
await browser.close()
console.log('ok')
